export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENTS_CONSTRUCTOR = 'GET_INGREDIENTS_CONSTRUCTOR';
export const ADD_INFO_INGREDIENT = 'OPENED_INGREDIENT';
export const REMOVE_INFO_INGREDIENT = 'CLOSED_INGREDIENT';
export const ORDER_NUMBER = 'ORDER_NUMBER';

